services:
  - type: web
    name: telegram-pixabay-bot
    env: python
    buildCommand: pip install --upgrade pip && pip install flask requests gunicorn python-telegram-bot && chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false  
      - key: PIXABAY_API_KEY
        sync: false
      - key: WEBHOOK_URL
        value: https://telegram-searo.onrender.com/webhook
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 5000
    healthCheckPath: /health
    numInstances: 1
    plan: free
    region: oregon
    scaling:
      minInstances: 1
      maxInstances: 1
